services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: ${UIDGID}
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ${PWD}/datasources:/etc/grafana/provisioning/datasources
      - ${PWD}/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  grafana-storage: {}